name: Build Jar

on: #[push]
  push:
    paths: 
      - 'src/*.java'
      - 'src/build/*.sh'
     # - '.github/workflows/*.yml'
 
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [16, 15, 14, 13, 12, 11, 10, 9, 8, 7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build
      run: cd src/build/; ./build.sh
    - name: Run
      run: java -jar src/build/acp_commander.jar -f
      
  deploy:   
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
    - uses: actions/checkout@v1
    - name: setup oldest supported JDK for build
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    
    - name: Build
      run: cd src/build/; ./build.sh
    - name: copy
      run: cp src/build/acp_commander.jar .
    - name: set git user name
      run: git config user.name "workflow@github" 
    - name: set git user email
      run: git config user.email "workflow@github" 
    - name: commit
      run: git commit -m "generate jar from latest source" acp_commander.jar
    - name: push
      run: git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:master
